[config]
version = "2"

[c8y]
root_cert_path = "@CONFIG_DIR@/ca-certificates.crt"
# Use basic auth if credentials file is present, otherwise use certificates
auth_method = "auto"
credentials_path = "@CONFIG_DIR@/credentials.toml"

[az]
root_cert_path = "@CONFIG_DIR@/ca-certificates.crt"

[aws]
root_cert_path = "@CONFIG_DIR@/ca-certificates.crt"

[mqtt.bridge]
built_in = true

[logs]
path = "/var/log/tedge"

[tmp]
path = "/tmp"

[data]
path = "/tmp/tedge"

[log]
plugin_paths = ["@CONFIG_DIR@/log-plugins", "/usr/share/tedge/log-plugins"]

[diag]
plugin_paths = ["@CONFIG_DIR@/diag-plugins", "/usr/share/tedge/diag-plugins"]
